float:
  euclidean:
  - base_args: {}
    constructor: CSPG
    disabled: false
    docker_tag: ann-benchmarks-cspg
    module: ann_benchmarks.algorithms.cspg
    name: 'cspg'
    run_groups:
      cspg_2_32_1_125_0-5:
        args: {m: 2, index_args: [32, 1, 125, 0.5]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      cspg_2_32_1-1_125_0-5:
        args: {m: 2, index_args: [32, 1.1, 125, 0.5]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      cspg_2_32_1-2_125_0-5:
        args: {m: 2, index_args: [32, 1.2, 125, 0.5]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      cspg_2_64_1_125_0-5:
        args: {m: 2, index_args: [64, 1, 125, 0.5]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      cspg_2_64_1-1_125_0-5:
        args: {m: 2, index_args: [64, 1.1, 125, 0.5]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      cspg_2_64_1-2_125_0-5:
        args: {m: 2, index_args: [64, 1.2, 125, 0.5]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]

