float:
  euclidean:
  - base_args: {}
    constructor: CSPG
    disabled: false
    docker_tag: ann-benchmarks-cspg
    module: ann_benchmarks.algorithms.cspg
    name: 'cspg'
    run_groups:
      cspg_2_64_1-2_128_0-5:
        args: {m: 2, index_args: [[64, 1.2, 128, 0.5]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]