float:
  euclidean:
  - base_args: {}
    constructor: DiskANN
    disabled: false
    docker_tag: ann-benchmarks-diskann
    module: ann_benchmarks.algorithms.diskann
    name: 'diskann'
    run_groups:
      group1:
        args: {m: 1, index_args: [[32, 1.2, 64, 0]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      group2:
        args: {m: 1, index_args: [[64, 1.2, 128, 0]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]