float:
  euclidean:
  - base_args: {}
    constructor: CSPG_DiskANN
    disabled: false
    docker_tag: ann-benchmarks-cspg_diskann
    module: ann_benchmarks.algorithms.cspg_diskann
    name: 'cspg_diskann'
    run_groups:
      group1:
        args: {m: 2, index_args: [[32, 1.2, 64, 0.5]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      group2:
        args: {m: 2, index_args: [[64, 1.2, 128, 0.5]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]