float:
  euclidean:
  - base_args: {}
    constructor: CSPG_NSG
    disabled: false
    docker_tag: ann-benchmarks-cspg_nsg
    module: ann_benchmarks.algorithms.cspg_nsg
    name: 'cspg_nsg'
    run_groups:
      group1:
        args: {m: 2, index_args: [[32, 256, 0.5]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      group2:
        args: {m: 2, index_args: [[64, 256, 0.5]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]