float:
  euclidean:
  - base_args: {}
    constructor: CSPG_HCNNG
    disabled: false
    docker_tag: ann-benchmarks-cspg_hcnng
    module: ann_benchmarks.algorithms.cspg_hcnng
    name: 'cspg_hcnng'
    run_groups:
      group1:
        args: {m: 2, index_args: [[3, 15, 1000, 0.5]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]
      group2:
        args: {m: 2, index_args: [[3, 15, 1250, 0.5]]}
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300]]